### ISSUE TITLE
Avoid creating .atlasmap_data folder in local git repository for users using VS Code "folders"

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#121]
the current implementation is using workspace.rootpath. it is a problem when Users are using a specific folder pointing to a git repo (one of the main user flow with VS Code as far i know), it will create the .atlasmap_data inside the local git repository and then pollute the project.
I think this way is fine only when users are using the "Workspace" concept of VSCode and not the "folder" concept.

see https://github.com/jboss-fuse/vscode-atlasmap/pull/117/files#r295771875

**Comment by lhein** [comment]
So the question is where to put the folder. I'd rather prevent using temp folders. So an idea would be to use the user home as a default root and put the configured folder under that root. Wdyt?

**Comment by apupier** [comment]
based on https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage
if I understood well our use case and the description in the documentation, I think we should go with ExtensionContext.storagePath

**Comment by lhein** [comment]
I removed the directory check in the test util method as I saw no obvious way to access the extension context from within the test. There is a context variable but that doesn't seem to be the extension context.

**Comment by lhein** [comment]
I also removed the configuration possibility for the folder where AtlasMap stores data. It became obsolete because we are using the extension storage path now followed by a fixed folder name.
