### ISSUE TITLE
Create UI tests

### ISSUE THREAD

**Issue by jkopriva** [jboss-fuse/vscode-atlasmap#140]
Create ui tests with vscode-extension-tester (https://github.com/jrichter1/vscode-extension-tester).
Tests are defined here: https://issues.jboss.org/browse/FUSEQE-4996

**Comment by jkopriva** [comment]
@apupier can you please assign this one to me? Thank you!
(I do not have permissions)

**Comment by apupier** [comment]
Can you ask to be added in https://github.com/orgs/jboss-fuse/teams/developers/members so that next time you can do it yourself please?

**Comment by jkopriva** [comment]
Add testcase for #137
