### ISSUE TITLE
Check project license and add copyright

### ISSUE THREAD

**Issue by jkopriva** [jboss-fuse/vscode-atlasmap#143]
In source files is missing copyright. We should add it in every source file and also check, if we have correct license.

**Comment by jkopriva** [comment]
Hi @lhein, I was looking into license and in my opinion we should switch licence to EPL v1, because requirements.ts file copied from vscode-java project, which uses EPL license. WDYT?

**Comment by lhein** [comment]
@apupier @paoloantinori opinions?
