### ISSUE TITLE
Preinstall script should run as postinstall

### ISSUE THREAD

**Issue by jkopriva** [jboss-fuse/vscode-atlasmap#145]
Preinstall script requires "mvn-artifact-download", this package is downloaded when running npm install. We should try to run preinstall script as postinstall, when all dependencies are available.

Background: user needs to run "npm install --ignore-scripts ". For new users it is confusing, because it is not documented. It would be easier for new users if he can skip this step and run only "npm install". Or we should mention that user needs to run "npm install --ignore-scripts " in documentation.

**Comment by apupier** [comment]
done https://github.com/jboss-fuse/vscode-atlasmap/blob/61081704372582d4f23137723636305c2d9d2191/package.json#L91
