### ISSUE TITLE
Warn user when atlasmap is already started

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#17]

**Comment by lhein** [comment]
> In a second iteration, we can give him option to free the port 

I don't see how you would force free a port. You will have to pick a different port in that case.

**Comment by lhein** [comment]
https://github.com/jboss-fuse/vscode-atlasmap/pull/40 is now showing an error message if the port we specify for local atlasmap is already in use. Will that be sufficient for this issue? If not, what else do u have in mind?

**Comment by apupier** [comment]
> #40 is now showing an error message if the port we specify for local atlasmap is already in use. Will that be sufficient for this issue? If not, what else do u have in mind?

I think the message can be even better but as we are working to get rid of letting user specifying the port, no need to invest more time on this.
If you agree, we can close this issue.
