### ISSUE TITLE
Allow user to specify port when starting atlasmap

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#18]

**Comment by lhein** [comment]
it seems atlasmap-standalone uses an environment variable for specifying the port to use.

See https://github.com/atlasmap/atlasmap/blob/master/standalone/src/main/java/io/atlasmap/standalone/Application.java#L32

**Comment by apupier** [comment]
to be more precise it is using Spring Environment context property which can be:

> The properties source can be java.util.Properties, loaded from a file or Java system/env properties or java.util.Map.
> 
> If we are in the Servlet container environment, the source can be javax.servlet.ServletContext or javax.servlet.ServletConfig.
> 

https://www.logicbig.com/tutorials/spring-framework/spring-core/spring-env-properties.html

**Comment by lhein** [comment]
without checking the details, do u know if there is a way to fill that spring context env with variables from cmd line?

**Comment by lhein** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-change-the-http-port

**Comment by lhein** [comment]
obsolete
