### ISSUE TITLE
Allow user to specify url when opening Atlasmap

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#19]

**Comment by lhein** [comment]
Yes, that would be nice. Similar to how yeoman displays defaults for inputs and changes to these defaults trigger an update to the stored settings.

**Comment by lhein** [comment]
The current behavior implemented is as follows:

user calls Open AtlasMap command
user is asked for AtlasMap URL (the default of the input field is what we stored in the settings)
user is asked for AtlasMap port (the default of the input field is what we stored in the settings)
if the defaults differ from the entered values the stored settings will be updated with those values
a test http request is issued to the provided url
on a positive response the browser will be openend
on a negative repsonse an error message will be shown in vscode
