### ISSUE TITLE
Provide icon for extension

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#21]
improve marketplace visibility and also in "installed" plugin view

https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-integration

**Comment by apupier** [comment]
currently with the default VS Code Extension greyed icon:
![image](https://user-images.githubusercontent.com/1105127/51168190-d6deaa80-18a8-11e9-987d-757a658b7a2c.png)

**Comment by apupier** [comment]
@igarashitm is there already a specific icon for AtlasMap?
- if yes, can you point me to it?
- if no, is it planned?
-- if planned, can you point me to the issue for that?
-- if not planned, i'm wondering if what is best: use Syndesis icon? use Red Hat Fuse icon? stay without icon?

**Comment by igarashitm** [comment]
We'll get an icon at some point, but no public tracking at this moment. In the meantime this autogenerated icon is the representative.

**Comment by apupier** [comment]
we now have the generic Red Hat integration icon https://github.com/jboss-fuse/vscode-atlasmap/blob/master/icons/icon128.png

![image](https://user-images.githubusercontent.com/1105127/64237070-eb38eb80-cefb-11e9-99ba-b3c3857683ed.png)

we will recreate another issue for a specific AtlasMap one when it will be available
