### ISSUE TITLE
Configure SonarCloud check

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#3]

**Comment by lhein** [comment]
provided via 5b51baf4efe865239003c00d233b1ec88e6b36e8

**Comment by apupier** [comment]
I don't see the sonarcloud entry on  https://sonarcloud.io/dashboard?id=vscode-atlasmap

seems the sonar scanner has not run: https://travis-ci.org/jboss-fuse/vscode-atlasmap/jobs/464265628#L500

**Comment by lhein** [comment]
interesting....branch was master but it was also a PR
