### ISSUE TITLE
Have Open Command using WebView API

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#36]
currently opening in default system browser

**Comment by apupier** [comment]
awaiting https://github.com/atlasmap/atlasmap/issues/740

**Comment by apupier** [comment]
a new version of standalone has been released which is working: https://github.com/atlasmap/atlasmap/issues/744#issuecomment-461069805

**Comment by apupier** [comment]
to be fixed https://github.com/jboss-fuse/vscode-atlasmap/issues/69

**Comment by lhein** [comment]
implemented in #76
