### ISSUE TITLE
Fix Sonar analysis

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#45]
https://travis-ci.org/jboss-fuse/vscode-atlasmap/jobs/483291926#L560

8.04s$ if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then sonar-scanner; fi
INFO: Scanner configuration file: /home/travis/.sonarscanner/sonar-scanner-3.0.3.778/conf/sonar-scanner.properties
INFO: Project root configuration file: /home/travis/build/jboss-fuse/vscode-atlasmap/sonar-project.properties
INFO: SonarQube Scanner 3.0.3.778
INFO: Java 1.8.0_151 Oracle Corporation (64-bit)
INFO: Linux 4.4.0-101-generic amd64
INFO: User cache: /home/travis/.sonar/cache
INFO: Publish mode
INFO: Load global settings
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 7.372s
INFO: Final Memory: 6M/113M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Not authorized. Please check the properties sonar.login and sonar.password.

**Comment by apupier** [comment]
I updated the SONAR_TOKEN in the travis config.

the error is now:
```
ERROR: Error during SonarQube Scanner execution
ERROR: You're not authorized to run analysis. Please contact the project administrator.
```
@lhein Can you give me admin rights to JBoss Fuse Sonar organization please? https://sonarcloud.io/organizations/jboss-fuse/members

**Comment by lhein** [comment]
Why did u do that? The token was fine.

**Comment by apupier** [comment]
> Why did u do that? The token was fine.

to try to fix:
```
ERROR: Error during SonarQube Scanner execution
ERROR: Not authorized. Please check the properties sonar.login and sonar.password.
```
It leads me to think that the Token might be outdated or revoked so I tried with a new one.

**Comment by lhein** [comment]
I set that token some days back and I did not get that error.

**Comment by lhein** [comment]
u should have the admin rights now.

**Comment by apupier** [comment]
fixed with new token after adding "execute analysis" right to my account: https://travis-ci.org/jboss-fuse/vscode-atlasmap/builds/486933252#L674
