### ISSUE TITLE
Configure project to have automatic compilation

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#59]
it will avoid to manually call npm run compile or to manually call npm run watch or tsc watch

several references on internet, need to find the "correct", for instance:
https://github.com/Microsoft/vscode/issues/5878
https://www.michaelcrump.net/quick-tip-with-typescript-and-vscode/

**Comment by lhein** [comment]
This is easy to solve and I described it in the contributing.md already. 

`Enter npm run watch to monitor the project for changes and to rebuild automatically

    You can also click menu Terminal -> Run Task and then select npm:watch from the list
    Both ways this will make any manual compiling obsolete which is a great help
`

**Comment by lhein** [comment]
You can also use CTRL-SHIFT-B as far as I saw as a shortcut to run the build task which also automatically watches for changes and rebuilds the files on save.

**Comment by lhein** [comment]
Sadly I did not find a way yet to make VSCode do that automatically whenever it has a typescript project.

**Comment by apupier** [comment]
> Sadly I did not find a way yet to make VSCode do that automatically whenever it has a typescript project.

maybe not possible as VS Code is still a "baby" IDE. In this case, maybe just reporting the feature request would be already great.

**Comment by lhein** [comment]
I think VSCode wanted to be as open as possible and not force users into specific behaviours / project setups. That is what makes me think this is OK as IS.

**Comment by lhein** [comment]
but on the other side where is the problem in hitting CTRL + SHIFT + B? Its easy and works great.

**Comment by apupier** [comment]
> where is the problem in hitting CTRL + SHIFT + B?

it took several weeks so that I (we?) find it.
having Ctrl+Shift+B is a good first step but not having to think about compiling is simplifying even more the development.
