### ISSUE TITLE
use conditional wait in tests

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#61]
instead of `await new Promise(resolve => setTimeout(resolve, 15000));`

it will allow to have faster and more reliable tests

**Comment by apupier** [comment]
there is still at least one "sleep" _await new Promise(resolve => setTimeout(resolve, 3000));_ in the test code. I think it would be great to find a way to get rid of it.

**Comment by lhein** [comment]
I think its just a grace period for the port to become free again. But yeah, we can of course try to find a better way.
