### ISSUE TITLE
Provide smarter check for runnign AtlasMap instance

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#67]
in case another application isrunnign on port 8585, it believes that it is available.
By default JDT LS is starting on 8585 which is causing the Atlasmap not to be launched

**Comment by lhein** [comment]
I think that is no longer the case. I am looking for the port inside the info message from the server startup.

**Comment by apupier** [comment]
the issue occurred again for me right now.

**Comment by lhein** [comment]
I can't reproduce your issue. Please provide some steps to reproduce it.
