### ISSUE TITLE
Open Atlasmap UI pre-filled when opening an "atlasmap transformation" file

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#7]

**Comment by apupier** [comment]
@igarashitm i have few questions to 
What is the file that we need to provide, is it an *.adm file?
Is there a specific API to which we provide a parameter in URI including the path to the filesystem? or to which we provide the content of the file?

**Comment by igarashitm** [comment]
The file actually required to run camel-atlasmap is the mapping definition file `atlas-mapping.xml` which is placed in a *.adm archive. *.adm is a zip file and you can see `atlas-mapping.xml` if you unzip the *.adm file. It needs to be fed in a classpath when camel route runs.

Example:
https://github.com/atlasmap/atlasmap/blob/master/camel/src/test/resources/org/apache/camel/component/atlasmap/AtlasMapComponentTest-context.xml#L11

**Comment by igarashitm** [comment]
mapping definition file is resolved from classpath when a camel route runs. At design time mapping definition file is an output from UI, or you just import .adm file to restore already created mapping into UI.

**Comment by lhein** [comment]
I think the question is more how we can deliver the mapping file to the atlasmap UI and backwards.

**Comment by apupier** [comment]
> I think the question is more how we can deliver the mapping file to the atlasmap UI and backwards. My impression is that it would make sense to somehow upload the whole adm archive to the web ui.

it depends on what needs to be pushed on an SCM for a Camel/Fuse Project using AtlasMap Data transformation.
this issue is intended to focus on opening in web UI. For the backward, I created https://github.com/jboss-fuse/vscode-atlasmap/issues/8

**Comment by igarashitm** [comment]
When you interact with AtlasMap UI, `.adm` file is the only option to import/export. The mapping definition XML itself doesn't have enough data to restore everything in UI.

**Comment by apupier** [comment]
the format of the project locally will surely be the same than what is on SCM.
The format on SCM is not yet defined for AtlasMap project

**Comment by apupier** [comment]
> When you interact with AtlasMap UI, `.adm` file is the only option to import/export. The mapping definition XML itself doesn't have enough data to restore everything in UI.

so you go for having the .adm file commited in SCM? No exploded archive for instance?

**Comment by lhein** [comment]
@igarashitm only relying on the adm file sounds logical. So how do we get it from the local file system to the web ui?

**Comment by igarashitm** [comment]
I think that's your part :) but if you want to extract, then vscode plugin should do that. AtlasMap UI only import/export .adm file.

**Comment by igarashitm** [comment]
@lhein AtlasMap UI has an import button, not sure how to poke it via vscode.

**Comment by apupier** [comment]
> I think that's your part :) but if you want to extract, then vscode plugin should do that. AtlasMap UI only import/export .adm file.

I don't understand why it is our part.
How the camel route with a data transformation in it can be built? Does it require a .adm file?

**Comment by apupier** [comment]
trying to summarize what @lhein reported during Fuse Tooling Engineering meeting from his direct discussions with Atlasmap (part of?) team:

The .adm file will stay the file that which be commited in Source Code Management even if it will hard for users to review modifications

The flow when a user wants to open the .adm file is:
- a user double-click or right-click open on the .adm file in VS Code
- the .adm file is copied to a specific location
- the browser is opened with a specific URL with parameter to the specific location/file. @igarashitm what is this API? is it already available?
- the user modify the data transformation in the UI
- then 2 iterations:
-- iteration 1: user is exporting the adm from UI and copying back to the project
-- iteration 2: will be handled with https://github.com/jboss-fuse/vscode-atlasmap/issues/8
--- when user is modifying the Data Transformation in UI , it is automatically saved to the .adm file in a specific location
--- VS Code extension is watching the file to detect when it is updated and copying it back to the workspace

**Comment by lhein** [comment]
This is currently a moving target. Nothing is yet set in stone. I will update the issue as soon as we reach an agreement.

**Comment by apupier** [comment]
> * the browser is opened with a specific URL with parameter to the specific location/file. @igarashitm what is this API? is it already available?

there is no specific URL for specific location/file because AtlasMap is handling a single file Data Transformation at a time. Created https://github.com/jboss-fuse/vscode-atlasmap/issues/72 for a following iteration to be able to edit several *.adm files simultaneously.

**Comment by apupier** [comment]
> * the .adm file is copied to a specific location

the place where it is copied will be specified with a system property: https://github.com/atlasmap/atlasmap/issues/755

**Comment by lhein** [comment]
PR ready and waiting for AtlasMap supporting that feature to finally test it.

**Comment by apupier** [comment]
PR for the AtlasMap side: https://github.com/atlasmap/atlasmap/pull/793
