### ISSUE TITLE
Created vsix does not find command

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#70]
Build the vsix for vscode-atlasmap locally
When launching the debug instance, it is working fine. If i build the vsix, install it and then try to use the "Open AtlasMap" I have an error message "command 'atlasmap.start' not found"
I got a message that the extension has been successfully installed.
![image pasted at 2019-2-11 16-21](https://user-images.githubusercontent.com/1105127/52573362-48633780-2e1a-11e9-84a7-c863ef7e00c0.png)

**Comment by apupier** [comment]
I tried with the first commit containing the commands and it was already not working.

**Comment by lhein** [comment]
reason was that the dependencies where not correctly listed in dependencies / devDependencies. Fix provided with PR #73
