### ISSUE TITLE
Support editing of more than one ADM file simultaneously

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#72]
currently AtlasMap is supporting a single file at a time.
VS Code AtlasMap is launching a single instance with always the same url.

several possibilities:
- launch a different AtlasMap instance for each *.adm file
  - solve resource issue (500Mo minimum per instance)
  - solve time to start (several seconds to wait when opening an editor)
    - Protean/graalVM native images?
    - pre-start an instance (so have one more started than the number of editors opened)
- implement support of several *.adm files in AtlasMap

**Comment by lhein** [comment]
I think that should be fixed in AtlasMap. Hiram also agreed that this is not a good situation.

**Comment by apupier** [comment]
covered when implemented https://issues.redhat.com/browse/FUSETOOLS2-50
