### ISSUE TITLE
Problems when working with AtlasMapUI v0.1.0

### ISSUE THREAD

**Issue by Yulya177** [jboss-fuse/vscode-atlasmap#755]
Good day! In the new version of the plugin, there are problems when opening the atlasmap template - it does not open either in the environment or on the web. This is due to the incorrect operation of the "replace" function when defining a port for opening AtlasMap.
In the script: ".vscode\extensions\redhat.atlasmap-viewer-0.1.1\out\extension.js"
`const realPort = withoutPrefix.replace(' ###\n', '');`
When replacing this line with
`const realPort = withoutPrefix.substring(0,withoutPrefix.indexOf(' ###'));`
everything works correctly.

**Comment by apupier** [comment]
Can you precise on which OS you are?
Can you precise what you mean by "on the web"? there is no more the option to open on an external browser automatically, even thoyugh if ypu retrieve the correct port you can type address directly in the browser.

**Comment by Yulya177** [comment]
I use Windows 10. Sorry for the inconsistency, indeed, the template should not open automatically in the browser. Template won't open in VS Code Editor

**Comment by apupier** [comment]
Can you provide the template file please? (or a simplified one which is reproducing the issue)

Can you provide the content of the Output "AtlasMap server" and "AtlasMap extension" please?

**Comment by Yulya177** [comment]
[AtlasMap Server.log](https://github.com/jboss-fuse/vscode-atlasmap/files/7735292/AtlasMap.Server.log)
[test.zip](https://github.com/jboss-fuse/vscode-atlasmap/files/7735358/test.zip)
But I don't know where to look at the "AtlasMap extension"

**Comment by apupier** [comment]
On Fedora, I can open the provided adm so I guess it is a windows specific bug. I guess the return to line is different. (but a \n shoudl handle all cases already). Or there is no return to line because there are different output, for me, it is finishing with:

```
2021-12-21 10:23:34.471  INFO 1231824 --- [           main] io.atlasmap.standalone.Application       : ### AtlasMap Data Mapper UI 2.4.0-M.2 started at port: 42867 ###
2021-12-21 10:23:34.629  INFO 1231824 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-12-21 10:23:34.630  INFO 1231824 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-12-21 10:23:34.631  INFO 1231824 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
```
in the attached log, there isn't the last 3 lines (and so no newline after the ###)
