### ISSUE TITLE
Have internal WebView used by default

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#84]
currently it opens by default on external browser.

before doing that QE needs to check if there is no blockers.

known issue:

- blockers:
  - standby QE check
  - Error when trying to import a jar https://github.com/atlasmap/atlasmap/issues/771 [SOLVED]
- non-blockers:
  - blank column on each side https://github.com/jboss-fuse/vscode-atlasmap/issues/69 [SOLVED]

**Comment by lhein** [comment]
@tsedmik any update on the QE testing?

**Comment by lhein** [comment]
Since we added a good amount of tests and also tested manually quite a good amount I would think we are fine to switch the default. @apupier ?

**Comment by apupier** [comment]
> Since we added a good amount of tests and also tested manually quite a good amount I would think we are fine to switch the default. @apupier ?

I would wait for the answer of @tsedmik depending when QE will have time to test it more, I think we can wait a bit more.

**Comment by tsedmik** [comment]
@lhein @apupier Not tested so far :-(. I've found human resources for testing AtlasMap for VS Code ;-). @jkopriva could you please look at this issue?

**Comment by jkopriva** [comment]
@lhein @apupier I have tried both:  atlasmap/atlasmap#771 and https://github.com/jboss-fuse/vscode-atlasmap/issues/69 without issues.

**Comment by apupier** [comment]
@jkopriva have you played a bit the AtlasMap when embedded inside VS Code? Does it behave correctly? As we don't have a lot of knowledge on AtlasMap capabilities, we are not confident if everything is fine or not.

**Comment by jkopriva** [comment]
@apupier yes, I have tried to import schemas, create mapping, export mapping. I am planning to play with it more tomorrow from scratch. For me it is something completely new :)

**Comment by apupier** [comment]
@jkopriva have you played with it a bit more? I noticed no reported issue. i would say that given time we can go ahead and use the internal view as default one now.
