### ISSUE TITLE
Have AtlasMap server internal files written in workspace related space

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/vscode-atlasmap#85]
it is currently writing in current working directory of Java which is for instance  on my machine: "C:\Users\Aurelien Pupier\AppData\Local\Programs\Microsoft VS Code\target"

it would be better to have it created in a workspace related place:
- will allow to have several VS Code instance launched
- Data transformations from another workspace can leak
- avoids a potential name collision teh day VS Code is writing a target folder in its own space

Having it configurable will also allow to launch several AtlasMap instance.

**Comment by lhein** [comment]
Where does that folder configuration come from?

**Comment by apupier** [comment]
> Where does that folder configuration come from?

it is a folder used internally by AtlasMap server.

**Comment by apupier** [comment]
> It looks more like that needs to be changed in AtlasMap or do I miss something?

I created an issue in AtlasMap to have it configurable https://github.com/atlasmap/atlasmap/issues/775

**Comment by lhein** [comment]
awesome!

**Comment by pleacu** [comment]
Hey - I've pushed the addition of atlasmap.workspace to specify a workspace for a standalone AtlasMap.

i.e.
java -Datlasmap.workspace=/home/pleacu/temp/adm-workspace -jar atlasmap-standalone.jar

**Comment by lhein** [comment]
thanks for the heads up Paul. Will add it to the extension as soon as a new version of AtlasMap Standalone is available.
