### ISSUE TITLE
Support importing inspected xml schema

### ISSUE THREAD

**Issue by rkorytkowski** [jboss-fuse/vscode-atlasmap#87]
FHIR schemas are quite complex and each resource is composed of 3 xsds with inter-dependencies. In Syndesis we generate a single inspected xml schema file in the AtlasMap json format for each resource. See https://github.com/syndesisio/syndesis/blob/master/app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateResourceInspectionsMojo.java#L126-L138  The pre-processed schema can be easily and quickly loaded into AtlasMap via json config. 

We need to be able to import such an inspected json file into AtlasMap from the standalone UI. At the moment only a single schema or instance can be loaded.

@paoloantinori

**Comment by apupier** [comment]
@rkorytkowski thanks for the report, I think that it is related to Standalone UI and not specifically to VS Code integration, so I transferred the issue to the atlasmap/atlasmap repository.

**Comment by rkorytkowski** [comment]
Fair point.
